import MainContainer from "@/components/MainContainer/MainContainer";
import { Grid } from "@mui/material";
import Head from "next/head";
import AsideMenu from "@/components/AsideMenu/AsideMenu";

import { observer } from "mobx-react-lite";
import AuthGuard from "@/features/AuthGuard";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/admin-favicon.svg" />
      </Head>
      <main>
        <AuthGuard>
          <MainContainer sx={{ py: 5, minHeight: "calc(100vh - 187px)" }}>
            <Grid container>
              <Grid item xs={3}>
                <AsideMenu />
              </Grid>
              <Grid item xs={9}></Grid>
            </Grid>
          </MainContainer>
        </AuthGuard>
      </main>
    </>
  );
};

export default observer(HomePage);
