import MainContainer from "@/components/MainContainer/MainContainer";
import {
  Divider,
  Grid,
  ListItemIcon,
  ListItemText,
  MenuItem,
  MenuList,
  styled,
} from "@mui/material";
import Head from "next/head";
import AsideMenu from "@/components/AsideMenu/AsideMenu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainContainer sx={{ py: 5 }}>
          <Grid container>
            <Grid item xs={3}>
              <AsideMenu />
            </Grid>
            <Grid item xs={9}></Grid>
          </Grid>
        </MainContainer>
      </main>
    </>
  );
}
